export const HttpStatus = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS: 'PHONE_ALREADY_EXISTS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  INVALID_OTP: 'INVALID_OTP',
  INVALID_OTP_CODE: 'INVALID_OTP_CODE',
  OTP_EXPIRED: 'OTP_EXPIRED',
  ALREADY_VERIFIED: 'ALREADY_VERIFIED',
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  ITEM_NOT_AVAILABLE: 'ITEM_NOT_AVAILABLE',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  ITEMS_ALREADY_RESERVED_OR_SOLD: 'ITEMS_ALREADY_RESERVED_OR_SOLD',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  HOLD_ALREADY_EXTENDED: 'HOLD_ALREADY_EXTENDED',
  HOLD_EXPIRED: 'HOLD_EXPIRED',
  DEPOSIT_REQUIRED: 'DEPOSIT_REQUIRED',
  CANCEL_NOT_ALLOWED: 'CANCEL_NOT_ALLOWED',
  RETURN_WINDOW_EXPIRED: 'RETURN_WINDOW_EXPIRED',
  SHIPPING_FEE_REQUIRED: 'SHIPPING_FEE_REQUIRED',
  POLICY_NOT_ACCEPTED: 'POLICY_NOT_ACCEPTED',
  POLICY_VERSION_OUTDATED: 'POLICY_VERSION_OUTDATED',
  PUBLISH_REQUIREMENTS_NOT_MET: 'PUBLISH_REQUIREMENTS_NOT_MET',
  PRICE_LOCKED: 'PRICE_LOCKED',
  ITEM_IN_ACTIVE_ORDER: 'ITEM_IN_ACTIVE_ORDER',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
} as const;

export const SESSION_COOKIE_NAME = '2hand_customer_session';
export const ADMIN_COOKIE_NAME = 'admin_session';
export const SESSION_DURATION_DAYS = 400; // ADR 006: sliding 400 days
/** Cookie Max-Age in seconds (400 days). Express `maxAge` option needs ms. */
export const SESSION_MAX_AGE_SEC = 34560000;
export const SESSION_SLIDE_MIN_INTERVAL_MS = 60 * 60 * 1000; // 1 hour
